#/bin/bash
spark-submit --class SolutionToAsg4 ./cs226-asg4-bsun031.jar file:///Users/ericsun/IdeaProjects/cs226-asg4-bsun031/input/nasa.tsv 804571201 804571214
curl -v --data-urlencode "statement= drop dataset Nasa if exists; drop TYPE NasaType if exists;
       create type NasaType as closed {
            id: uuid,
            host: string,
                    logname: string,
                    time: bigint,
            method: string,
                    URL: string,
                    response: string,
                    bytes: double,
            referrer: string,
                    useragent: string
        };
        create dataset Nasa(NasaType) PRIMARY KEY id AUTOGENERATED;
        load dataset Nasa using localfs
                ((\"path\"=\"127.0.0.1:///Users/ericsun/nasa.tsv\"),
                        (\"format\"=\"delimited-text\"),
                        (\"delimiter\"=\"\t\"));" \
          --data pretty=true                     \
          --data client_context_id=xyz           \
          http://localhost:19002/query/service

curl -v --data-urlencode "statement=FROM Nasa GROUP BY response SELECT AVG(bytes) AS average, response;" \
          --data pretty=true                     \
          --data client_context_id=xyz           \
          http://localhost:19002/query/service | sed -n '4,17p' >> taskA.txt
echo -e "AsterixDB TaskA finished!\n"

curl -v --data-urlencode "statement=Select count(*) From Nasa where time >= 804571201 and time <= 804571214;" \
          --data pretty=true                     \
          --data client_context_id=xyz           \
          http://localhost:19002/query/service | sed -n '4,7p' >> taskB.txt
echo -e "TaskB finished!"
curl -v --data-urlencode "statement=create index timeIdx on Nasa(time);" \
          --data pretty=true                     \
          --data client_context_id=xyz           \
          http://localhost:19002/query/service
echo -e "Index on timestamp finished!\n"
curl -v --data-urlencode "statement=Select count(*) From Nasa where time >= 804571201 and time <= 804571214;" \
          --data pretty=true                     \
          --data client_context_id=xyz           \
          http://localhost:19002/query/service | sed -n '4,7p' >> taskC.txt
echo "TaskC finished!"
